# Default values for do500.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Create a helper to create a prefix if one isn't provided? Would help if we moved to shared clusters
prefix: ""

gitlab_app_name: "gitlab-ce"

namespaces:
  - name: do500-workspaces
  - name: do500-gitlab
#  - name: do500-slides

operators:
  - name: codeready-workspaces
    namespace: do500-workspaces
    subscription:
      channel: latest
      approval: Automatic
      operatorName: codeready-workspaces
      sourceName: redhat-operators
      sourceNamespace: openshift-marketplace
      csv: crwoperator.v2.5.0
    operatorgroup:
      create: true

gitlab:
  namespace: do500-gitlab
  root_password: Password123
  imagestreams:
    - name: "gitlab-ce"
      tag_name: "gitlab-12.8.7"
      stream_uri: "gitlab/gitlab-ce:12.8.7-ce.0"
    - name: "gitlab-ce-redis"
      tag_name: "5.0.4"
      stream_uri: "redis:5.0.4-alpine"
    - name: "postgresql"
      tag_name: "latest"
      stream_uri: "registry.redhat.io/rhscl/postgresql-96-rhel7"
  ldap:
#    port: "389"
#    base: "dc=CORP,dc=EXAMPLE,dc=COM"
#    uri: "MY-LDAP.example.corp.com"
#    user_filter: ""
#    validate_certs: "false"
    secret_name: my-ldap-secret-name
#    bind_dn: uid=ldap-admin,cn=users,cn=accounts,dc=CORP,dc=EXAMPLE,dc=COM

crw:
  namespace: do500-workspaces
  name: "codeready-workspaces"
#  devRegImage: "quay.io/rht-labs/devfileregistry:test"
  tlsSupport: true
  properties:
    CHE_LIMITS_USER_WORKSPACES_COUNT: "2"
    CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "1"
    CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: "Always"
    CHE_DOCKER_ALWAYS__PULL__IMAGE: "true"
    CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: "3072"
    CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "-1"

#docs:
#  name: do500-slides
#  namespace: do500-slides 
#  build:
#    source_context_dir: "slides"
#    source_repo: "https://github.com/rht-labs/enablement-docs"
#    s2i_name: "nodejs"
#    s2i_tag: "10"
