---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collection:
    logs:
      fluentd: {}
      type: fluentd
  logStore:
    elasticsearch:
      resources:
        {{- if .Values.logging.elasticsearch.requests }}
        requests:
          cpu: {{ .Values.logging.elasticsearch.requests.cpu }}
          memory: {{ .Values.logging.elasticsearch.requests.memory }}
        {{- end }}
        {{- if .Values.logging.elasticsearch.limits }}
        limits:
          cpu: {{ .Values.logging.elasticsearch.limits.cpu }}
          memory: {{ .Values.logging.elasticsearch.limits.memory }}
        {{- end }}
      nodeCount: {{ .Values.logging.elasticsearch.nodeCount }}
      {{- if .Values.logging.nodeSelector }}
      nodeSelector:
        {{ .Values.logging.nodeSelector.key }}: {{ .Values.logging.nodeSelector.value }}
      {{- end }}
      tolerations:
{{ toYaml .Values.logging.tolerations | indent 6 }}
      redundancyPolicy: {{ .Values.logging.elasticsearch.redundancyPolicy }}
      {{- if .Values.logging.elasticsearch.storage }}
      storage:
        size: {{ .Values.logging.elasticsearch.storage.size }}
        storageClassName: {{ .Values.logging.elasticsearch.storage.class }}
      {{- else }}
      storage: {}
      {{- end }}
    retentionPolicy:
      application:
        maxAge: {{ .Values.logging.elasticsearch.retentionPolicy.application }}
    type: elasticsearch
  managementState: Managed
  visualization:
    kibana:
      {{- if .Values.logging.nodeSelector }}
      nodeSelector:
        {{ .Values.logging.nodeSelector.key }}: {{ .Values.logging.nodeSelector.value }}
      {{- end }}
      tolerations:
{{ toYaml .Values.logging.tolerations | indent 6 }}
      replicas: {{ .Values.logging.kibana.replicas | default "1" }}
    type: kibana