apiVersion: v2
name: tl500
description: A Helm chart for Kubernetes
type: application
version: 0.0.7
appVersion: 0.0.1
maintainers:
  - name: eformat
  - name: tylerauerbeck
  - name: jacobsee
  - name: jtudelag
  - name: ckavili
  - name: springdo
dependencies:
  - name: sealed-secrets
    version: "1.16.1"
    repository: https://bitnami-labs.github.io/sealed-secrets
    condition: sealed-secrets.enabled
  - name: stackrox-chart
    version: "0.0.2"
    repository: https://redhat-cop.github.io/helm-charts
    condition: stackrox.enabled
  - name: gitops-operator
    version: "0.2.4"
    repository: https://redhat-cop.github.io/helm-charts
    condition: gitops-operator.enabled