apiVersion: v2
name: tl500-course-content
description: A Helm chart for Kubernetes
type: application
version: 0.0.7
appVersion: 0.0.1
maintainers:
  - name: eformat
  - name: jacobsee
  - name: jtudelag
  - name: ckavili
  - name: springdo
