{{- if .Values.crwv2 }}
apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  name: {{ .Values.crwv2.name | default "codeready-workspaces" | quote }}
  namespace: {{ .Values.crwv2.namespace | default "tl500-workspaces" | quote }}
spec:
  components:
    database:
      externalDb: false
    metrics:
      enable: false
    cheServer:
      debug: false
      logLevel: INFO
      extraProperties: {{ toYaml .Values.crwv2.properties | nindent 8 | default "" }}
  devEnvironments:
    startTimeoutSeconds: 300
    secondsOfRunBeforeIdling: {{ .Values.crwv2.secondsOfRunBeforeIdling | default -1 }}
    secondsOfInactivityBeforeIdling: {{ .Values.crwv2.secondsOfInactivityBeforeIdling | default -1 }}
    maxNumberOfWorkspacesPerUser: -1
    disableContainerBuildCapabilities: true
    defaultNamespace:
      autoProvision: true
      template: <username>-devspaces
    storage:
      perUserStrategyPvcConfig:
        claimSize: 2Gi
      pvcStrategy: per-workspace
{{- end }}
